# Generated by Django 4.2.4 on 2023-09-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('year_lanzamientoo', models.PositiveIntegerField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='discos/')),
                ('url_compra', models.URLField(blank=True)),
            ],
        ),
    ]
