# Generated by Django 4.2.4 on 2023-09-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0002_discos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('instrumento', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='biografia/')),
            ],
        ),
    ]
